### ISSUE TITLE
Home and Our Team pages

### ISSUE THREAD

**Issue by itsKhadeer** [itsKhadeer/Events-Website#2]
### Description
This GitHub issue is created to track the implementation of "Home" and "Our Team" pages in the project.

### Tasks
  - [ ] Create proper components for the Pages like header, footer, page wrapper etc
  - [ ] Design the page and components so that the page looks good, we prefer you to use figma for this.
  - [ ] make the pages responsive for both pc and mobile.

### Additional Information
- The pages should be styled using Tailwind CSS.
- Ensure proper navigation links are added for easy access to these pages.
- Feel free to create your onw assets in figma or from other sources

### Deadline
[TBD]

**Assigned Developers:**
- [ ] TBD

**Comment by A-nirvana** [comment]
I would like to work on this issue please assign it to me

**Comment by hirakRajbonshi** [comment]
Hey, I would like to work on this project.

**Comment by itsKhadeer** [comment]
> I would like to work on this issue please assign it to me

sure, when can you give the pr?

**Comment by A-nirvana** [comment]
I can give the pr by 30 Jan IST, I'll start working on it as soon as you assign it to me. And if you could then please provide some content that should be there like the logo or other displayed content. Thanks

**Comment by tanmay958** [comment]
hey i would like to work on this project,  i can deliver this within 2 days i need some information before hand bdw like is it like a event management website i mean people can come and register their event and other people can enroll for their event or is it like a specific event page if it is give me the context

**Comment by itsKhadeer** [comment]
> I can give the pr by 30 Jan IST, I'll start working on it as soon as you assign it to me. And if you could then please provide some content that should be there like the logo or other displayed content. Thanks

sure Join the discord : <a href="https://discord.gg/eYmCp5VAJj">Discord<a>
we will discuss there
